import mongoose from "mongoose";

export const categories = [
  "rent",
  "mortgage",
  "utilities",
  "repairs",
  "furniture",
  "household_goods",
  "groceries",
  "personal_care",
  "clothing",
  "electronics",
  "appliances",
  "public_transport",
  "fuel",
  "car_maintenance",
  "taxi",
  "parking",
  "vehicle_insurance",
  "restaurants",
  "cafes",
  "fast_food",
  "delivery",
  "medicine",
  "doctor",
  "dentist",
  "sports",
  "insurance_health",
  "courses",
  "books",
  "school",
  "university",
  "training",
  "cinema",
  "theatre",
  "concerts",
  "games",
  "subscriptions",
  "hobbies",
  "flights",
  "hotels",
  "tours",
  "visa",
  "travel_insurance",
  "loans",
  "taxes",
  "insurance",
  "fees",
  "investments",
  "gifts",
  "charity",
  "family_support",
  "pet_food",
  "pet_care",
  "vet",
  "other",
];

const expenseSchema = new mongoose.Schema({
  budgetId: { type: mongoose.Schema.Types.ObjectId, ref: "Budget" },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  title: { type: String, required: true },
  amount: { type: Number },
  confirmed: { type: Boolean, default: false },
  comment: { type: String },
  priority: { type: Number, min: 1, max: 3, default: 1 },
  frequency: {
    type: String,
    enum: ["once", "daily", "weekly", "monthly", "yearly"],
    default: "daily",
  },
  scope: { type: String, enum: ["personal", "shared"], default: "personal" },
  date: { type: Date },
  createdAt: { type: Date, default: Date.now },
  category: { type: [String], enum: categories },
});

export const ExpenseModel = mongoose.model("Expense", expenseSchema);
